name: push-main

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.source.outputs.TAG }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: last
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}

      - name: Tag name
        id: source
        run: |
          echo ::set-output name=TAG::${{ steps.last.outputs.release }}-${{ github.run_number }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sudoblock/icon-tracker-frontend:latest, sudoblock/icon-tracker-frontend:${{ steps.source.outputs.TAG }}

  push_refs:
    runs-on: ubuntu-latest
    needs: docker
    strategy:
      max-parallel: 1
      matrix:
        include:

#          - cluster: prod-sng
#            network_name: mainnet
#            network_version: v2
          - cluster: prod-sng
            network_name: berlin
            network_version: v2
          - cluster: prod-sng
            network_name: lisbon
            network_version: v2
#          - cluster: prod-ams
#            network_name: mainnet
#            network_version: v2
#          - cluster: prod-ams
#            network_name: berlin
#            network_version: v2
#          - cluster: prod-ams
#            network_name: lisbon
#            network_version: v2

    steps:
      - name: Checkout charts repo
        uses: actions/checkout@v2
        with:
          repository: sudoblockio/icon-charts
          ref: main
          path: charts
          token: ${{ secrets.ICON_CHARTS_PAT }}

      - name: Git pull the latest
        run: |
          git pull
        working-directory: charts

      - name: Update ${{ matrix.cluster }}/${{ matrix.network_name }}-${{ matrix.network_version }} image tags file
        uses: fjogeleit/yaml-update-action@master
        with:
          workDir: charts
          repository: sudoblockio/icon-charts
          valueFile: 'deployments/${{ matrix.cluster }}/${{ matrix.network_name }}-${{ matrix.network_version }}/tracker-frontend/tags.yaml'
          propertyPath: 'deployment.image.tag'
          value: ${{needs.docker.outputs.tag}}
          branch: main
          createPR: 'false'
          updateFile: true
          message: "tracker frontend ${{ matrix.cluster }}/${{ matrix.network_name }}-${{ matrix.network_version }} deployment image version to ${{needs.docker.outputs.tag}}"
          token: '${{ secrets.ICON_CHARTS_PAT }}'